# stylua.toml defines the style applied to a lua file with the `stylua` CLI. To apply this specific
# configuration file, add the --config-path <path> to your formatting command. Alternatively, you can specify
# a configuration file with the `-f` flag.
#
# stylua -f ~/.config/stylua/stylua.toml <file>

# For a complete explanation of options see https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options
syntax = "All"
column_width = 110
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
space_after_function_names = "Never"
block_newline_gaps = "Never"

[sort_requires]
enabled = false
